version: 2.1
orbs:
  go: circleci/go@1.17
jobs:
  build:
    executor:
      name: go/default
      tag: "1.17"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
  main:
    jobs:
      - build
