version: 2.1
orbs:
  go: circleci/go@1.7.0
  codecov: codecov/codecov@3.2.2
jobs:
  build:
    executor:
      name: go/default
      tag: "1.17"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          coverprofile: coverprofile.out
      - codecov/upload:
          file: coverprofile.out
workflows:
  main:
    jobs:
      - build
